[tool.poetry]
name = "rubik-cube"
version = "0.1.0"
description = "this is a rest API for a timer for speedcubers"
authors = ["Santiago Benavides <sabenavidesc@udistrital.edu.co>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"
uvicorn = "^0.34.0"
fastapi = "^0.115.8"
numpy = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
